blog/urls.py
from django.urls import (
    path,
    include
)

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail import urls as wagtail_urls

from .views import index

urlpatterns = [
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('', index, name="blog_index"),
    path('', include(wagtail_urls)),
]

config/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)
from django.conf.urls.static import static

from .settings.base import (
    MEDIA_ROOT,
    MEDIA_URL,
)

urlpatterns = [
    path('__reload__', include('django_browser_reload.urls')),

    path('admin/', admin.site.urls),

    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),

    path('', include('public.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from .views import (
    index,
    projects,
    designs,
    content
)

app_name = 'portfolio'
urlpatterns = [
    path('', index, name="index"),
    path('projects', projects, name="projects"),
    path('experience', projects, name="experience"),
    path('designs', designs, name="designs"),
    path('content', content, name="content")
]

services/urls.py
from django.urls import path

from .views import (
    index
)

app_name = 'services'

urlpatterns = [
    path('', index, name="index"),
]

blog/models.py
from django.db import models

from wagtail.models import Page  # type: ignore
from wagtail.fields import StreamField  # type: ignore
from wagtail.blocks import (  # type: ignore
    RichTextBlock,
    StructBlock,
    ChoiceBlock,
    TextBlock
)
from wagtail.admin.panels import FieldPanel  # type: ignore
from wagtail.search import index  # type: ignore

import pygments  # type: ignore
from pygments import (  # type: ignore
    lexers,
    formatters
)


class CodeBlock(StructBlock):
    current_lexer = None

    language_choices = []

    for lexer in lexers.get_all_lexers():
        try:
            language_choices.append(
                (lexer[1][0], lexer[1][0])
            )
        except IndexError:
            continue

    language = ChoiceBlock(
        choices=language_choices,
        default='plain'
    )
    code = TextBlock(
        form_classname='monospace'
    )

    class Meta:
        template = 'blog/blocks/code_block.html'

    def get_context(
        self,
        value,
        parent_context=None
    ):
        context = super().get_context(
            value,
            parent_context=parent_context
        )
        lexer = lexers.get_lexer_by_name(
            value='language'
        )
        formatter = formatters.HtmlFormatter()
        highlighted_code = pygments.highlight(
            value['code'],
            lexer,
            formatter
        )
        context['highlighted_code'] = pygments.highlight(
            highlighted_code
        )
        return context


class BlogPostPage(Page):
    date: models.DateField = models.DateField("Post date")
    intro: models.CharField = models.CharField(
        max_length=500
    )
    hero_image: models.ForeignKey = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )
    body: StreamField = StreamField(
        [
            ('rich_text', RichTextBlock()),
            ('code', CodeBlock()),
        ],
        blank=True
    )
    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        FieldPanel('intro'),
        FieldPanel('hero_image'),
        FieldPanel('body'),
    ]


class BlogPostIndexPage(Page):
    subpage_types = ['blog.BlogPostPage']

    def get_context(self, request):
        context = super().get_context(request)
        context['posts'] = BlogPostPage.objects.all()
        return context

portfolio/models.py
import os

from django.db import models

from public.validators import (
    validate_icon_file_extension
)

class PreviewType(models.Model):
    icon = models.FileField(
        upload_to=os.path.join(
            'portfolio',
            'preview_types'
        ),
        validators=[validate_icon_file_extension]
    )
    name = models.CharField(
        max_length=100
    )
    display_name = models.CharField(
        max_length=100
    )
    
    created_on = models.DateTimeField(
        auto_now_add=True
    )
    
    updated_on = models.DateTimeField(
        auto_now=True
    )
    
    def __str__(self):
        return self.display_name

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(
        upload_to=os.path.join('portfolio', 'projects')
    )
    preview_url = models.URLField()
    preview_type = models.ForeignKey(
        'PreviewType',
        on_delete=models.DO_NOTHING
    )
    
    technologies = models.ManyToManyField(
        'Technology',
        blank=True
    )
    
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Technology(models.Model):
    CATEGORIES = [
        ('frontend', 'Frontend Tools'),
        ('backend', 'Backend Tools'),
        ('fullstack', 'Fullstack Frameworks'),
        ('mobile', 'Mobile Frameworks'),
        ('crossplatform', 'Crossplatform Frameworks'),
        ('database', 'Databases'),
        ('data_engineering', 'Data Engineering Tools'),
        ('devops', 'Dev Ops Tools'),
        ('language', 'Languages'),
        ('content_management_systems', 'Content Management Systems'),
        ('other', 'Other')
    ]
    
    name = models.CharField(max_length=100)
    display_name = models.CharField(max_length=100)
    icon = models.FileField(
        upload_to=os.path.join('portfolio', 'technologies'),
        validators=[validate_icon_file_extension],                         
    )
    
    category = models.CharField(
        max_length=100,
        choices=CATEGORIES,
        default='other'
    )
    
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'technologies'
    
    def __str__(self):
        return self.display_name

services/models.py
import os
from django.db import models

from public.validators import (
    validate_icon_file_extension
)

class Service(models.Model):
    name = models.CharField(max_length=100)
    display_name = models.CharField(max_length=100)
    image = models.FileField(
        upload_to=os.path.join('services', 'thumbnails'),
        validators=[validate_icon_file_extension],
    )
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from wagtail.urls import views

def index(request):
    return views.serve(
        request,
        '/'        
    )
    
def query(request, query):
    return views.serve(
        request,
        '/' + query
    )

portfolio/views.py
from django.shortcuts import render

from .models import (
    Project,
    Technology
)

def index(request):
    return projects(request)

def projects(request):
    projects = Project.objects.all()
    technologies = Technology.objects.all().order_by('category')
    
    context = {
        'projects': projects,
        'technologies': technologies
    }
    
    return render(
        request,
        'portfolio/pages/projects.html',
        context
    )
    
def designs(request):
    context = {}
    
    return render(
        request,
        'portfolio/pages/designs.html',
        context
    )
    

def content(request):
    context = {}
    
    return render(
        request,
        'portfolio/pages/designs.html',
        context
    )
    
def services(request):
    context = {}
    
    return render(
        request,
        'portfolio/pages/services.html',
        context
    )

services/views.py
from django.shortcuts import render

def index(request):
    context = {}
    
    return render(
        request,
        'services/pages/index.html',
        context
    )

blog/templates/blog/_base.html
{% extends 'public/_base.html' %}

{% block content %}
    <div class="flex flex-col h-full w-full overflow-y-hidden dark:bg-gray-800">
        <div class="w-full">
            {% include 'blog/search.html' %}
        </div>
        <div class="w-full flex-1 overflow-y-hidden">
            {% block app_content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/blocks/code_block.html
<div class="code-block">
    <pre class="language-python">{{ highlighted_code|safe }}</pre>
</div>

blog/templates/blog/blog_post/top_menu.html
<button
    x-data="{}"
    x-on:click="history.back()"
    type="button"
    class="p-2 hover:bg-secondary-100 rounded">
    <span class="sr-only">Back</span>
    <svg class="w-6 h-6 text-secondary-500 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
    </svg>
</button>

blog/templates/blog/blog_post_index/blog_post.html
{% load wagtailimages_tags %}
<a href="{{ post.url }}"
    class="block w-full margin-x-auto w-[90%] max-w-[600px] grid grid-cols-12 border border-1 border-gray-200 p-4 rounded hover:transform hover:scale-105 transition ease-in-out cursor:pointer">
    <div
        class="col-span-12 h-[200px] flex flex-col items-center justify-center">
        {% image post.hero_image max-2000x2000 class="object-contain h-full w-full" %}
    </div>
    <div
        class="flex flex-col flex-1 gap-2 col-span-12 h-full items-start justify-center p-4 overflow-y-hidden">
        <h3 class="text-lg text-primary-700 text-start font-bold">{{ post.title }}</h3>
        <div class="bg-primary-700 rounded-xl flex flex-row justify-center px-8">
            <p class="text-sm w-full text-white font-medium text-end">{{ post.date }}</p>
        </div>
        <p class="text-gray-800 text-start flex-1 overflow-y-auto">{{ post.intro }}</p>
    </div>
</a>

blog/templates/blog/blog_post_index_page.html
{% extends 'blog/_base.html' %}

{% block app_content %}
    <div class="w-full h-full flex flex-col gap-2 items-center start-center p-4 overflow-y-auto">
        {% for post in posts %}
            {% include './blog_post_index/blog_post.html' with post=post %}
        {% empty %}
            {% include 'public/404.html' with message="Looks like there's no blog posts yet." %}
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/blog_post_page.html
{% extends 'blog/_base.html' %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

{% block content %}
    <div class="h-full w-full md:w-[80%] max-w-[1200px] mx-auto flex flex-col overflow-y-auto">
        <div class="w-full p-4 flex flex-row gap-2 items-center justify-start">
            {% include './blog_post/top_menu.html' %}
            <h2 class="text-3xl flex-1 text-center text-primary-700 font-bold">{{ page.title }}</h2>
        </div>
        <div class="w-full p-4 flex flex-col gap-2 items-center justify-center">
            <div class="bg-primary-700 rounded-xl flex flex-row justify-center px-8">
                <p class="text-sm w-full text-white font-medium text-end">{{ page.date }}</p>
            </div>
            <div class="h-[300px] p-4 flex flex-row justify-center items-center">
                {% image page.hero_image max-2000x2000 class="rounded-xl p-4 object-contain h-[300px]" %}
            </div>
            <div class="w-full p-4 flex flex-row justify-center">
                <p class="text-gray-500">{{ page.intro }}</p>
            </div>
            <div class="w-full p-4 flex flex-col items-center gap-2 wagtail-richtext">
                {% include_block page.body %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/search.html
<div class="w-full p-4 flex flex-col items-center justify-center">
    <form
        class="w-full h-full flex flex-row items-center justify-center gap-2"
        action="/" method="get">
        <label
            for="blog-search"
            class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
        <div
            class="relative max-w-[600px] w-[80%] mx-auto">
            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
            </div>
            <input
                name="query"
                {% if query %}value="{{ query }}"{% endif %}
                type="search" id="blog-search"
                class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                placeholder="Search posts" required />
            <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Search</button>
        </div>
    </form>
</div>

portfolio/templates/portfolio/_base.html
{% extends 'public/_base.html' %}

portfolio/templates/portfolio/pages/projects/active_filters.html
<template x-for="technology in filter_technologies" x-cloak>
    <span x-text="technology" class="inline-flex block items-center justify-center px-2 py-1 me-1 text-xs font-bold leading-none text-secondary-100 dark:text-gray-900 bg-secondary-500 rounded"></span>
</template>

portfolio/templates/portfolio/pages/projects/filter_controls.html
<div class="p-2">
    <div>
        {% include './sidebar_search.html' %}
    </div>
    <template
        x-if="filter_technologies.length > 0">    
        <div
            class="flex flex-row justify-end">
            <button
                x-on:click="filter_technologies = []"
                type="button"
                class="text-secondary-500 hover:text-secondary-300 transition ease-in-out">
                <span
                    class="font-medium">Clear Filters</span>
            </button>
        </div>
    </template>
    <div class="block md:hidden">
        {% include './active_filters.html' %}
    </div>
    <div
        class="w-full flex flex-row justify-center py-2 md:hidden"
        x-bind:class="{
            'hidden': !filters_open,
        }">
        <button
            x-bind:disabled="filter_technologies.length === 0"
            type="button"
            class="bg-secondary-500 disabled:bg-secondary-300 disabled:text-gray-500 ring-1 ring-secondary-100 rounded px-2 hover:bg-secondary-300 transition ease-in-out p-2"
            x-on:click="filters_open = !filters_open">
            <span
                class="font-medium">Apply Filters</span>
        </button>
    </div>
</div>

portfolio/templates/portfolio/pages/projects/main.html
{% load static %}
<div class="h-full w-full flex flex-col items-center justify-center">
    {% include './main_header.html' %}
    <template
        x-if="filter_technologies.length > 0">
        <div
            class="w-full p-2 flex justify-center">
            {% include './active_filters.html' %}
        </div>
    </template>
    <div class="w-full flex-1 grid grid-cols-12 gap-2 overflow-y-auto items-center justify-center p-4">
        {% for project in projects %}
            {% include './project_item.html' with project=project %}
        {% empty %}     
            {% include 'public/404.html' with message="Looks like there's no projects yet." %}
        {% endfor %}
    </div>  
</div>

portfolio/templates/portfolio/pages/projects/main_header.html
<div class="w-full flex flex-row justify-end md:justify-center items-center">
    
    <div class="block md:hidden p-2">
        <button
            x-on:click="filters_open = !filters_open"
            type="button"
            x-bind:class="{
                'bg-secondary-200 ring-1 ring-secondary-100': filters_open,
            }"
            class="rounded px-2 hover:bg-secondary-300 transition ease-in-out p-2">
            <span class="sr-only">Filters</span>
            <svg class="w-6 h-6 text-secondary-500 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M18.796 4H5.204a1 1 0 0 0-.753 1.659l5.302 6.058a1 1 0 0 1 .247.659v4.874a.5.5 0 0 0 .2.4l3 2.25a.5.5 0 0 0 .8-.4v-7.124a1 1 0 0 1 .247-.659l5.302-6.059c.566-.646.106-1.658-.753-1.658Z"/>
            </svg>
        </button>
    </div>
</div>

portfolio/templates/portfolio/pages/projects/project_item.html
<div
    x-data="{
        technologies: [ {% for technology in project.technologies.all %} '{{ technology.name }}', {% endfor %} ]
    }"
    x-show="filter_technologies.every(technology => technologies.includes(technology))"
    class="z-1 mx-auto flex flex-col h-[320px] w-[360px] overflow-y-hidden md:w-full transition duration-300 ease-in-out col-span-12 md:col-span-6 lg:col-span-4 max-w-sm bg-white border border-gray-200 rounded shadow dark:bg-gray-800 dark:border-gray-700 hover:transform hover:scale-105 transition ease-in-out">
    <a href="{{ project.image.url }}" class="block h-[160px] w-full">
        <img class="rounded-t h-full w-full object-fill" src="{{ project.image.url }}" alt="{{ project.title }}" />
    </a>
    <div class="p-2 flex flex-col flex-1 overflow-y-hidden bg-white dark:bg-gray-900">
        <a href="{{ project.image.url }}">
            <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">{{ project.title }}</h5>
        </a>
        <div class="flex-1 flex flex-col justify-start items-end justify-end overflow-y-hidden">
            <p class="mb-3 font-normal text-sm text-gray-700 dark:text-gray-400 flex-1 overflow-y-auto w-full">{{ project.description }}</p>
            <div class="w-full flex flex-row justify-start">
                <a href="{{ project.preview_url }}" target="_blank" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-primary-700 rounded hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                    <img src="{{ project.preview_type.icon.url }}" alt="{{ project.title }} {{ project.preview_type.display_name }}" class="w-5 h-5 mr-2">
                    <span>View {{ project.preview_type.display_name }}</span>
                    <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                    </svg>
                </a>
            </div>
        </div>
    </div>
</div>

portfolio/templates/portfolio/pages/projects/sidebar.html
{% load static %}
<div class="h-full overflow-y-hidden flex flex-col bg-white dark:bg-gray-800" x-data="{ search: '' }">
    {% include './sidebar_controls.html' %}
    <div class="gap-2 flex flex-col overflow-y-auto p-4 flex-1">
    {% for technology in technologies %}
        {% ifchanged %}<h4 class="text-primary-700 dark:text-secondary-500 font-medium bold">{{ technology.get_category_display }}</h4>{% endifchanged %}
        {% include './sidebar_item.html' with icon="{{ technology.icon.url }}" title="{{ technology.display_name }}" name="{{ technology.name }}" %}
    {% endfor %}
    </div>
</div>

portfolio/templates/portfolio/pages/projects/sidebar_controls.html
<div class="p-2">
    <div>
        {% include './sidebar_search.html' %}
    </div>
    <template
        x-if="filter_technologies.length > 0">    
        <div
            class="flex flex-row justify-end">
            <button
                x-on:click="filter_technologies = []"
                type="button"
                class="text-secondary-500 hover:text-secondary-300 transition ease-in-out">
                <span
                    class="font-medium">Clear Filters</span>
            </button>
        </div>
    </template>
    <div class="block md:hidden">
        {% include './active_filters.html' %}
    </div>
    <div
        class="w-full flex flex-row justify-end py-2 md:hidden gap-2"
        x-bind:class="{
            'hidden': !filters_open,
        }">
        <button
            type="button"
            class="bg-secondary-500 disabled:bg-secondary-300 disabled:ring-0 ring-3 ring-secondary-300 disabled:text-gray-500 rounded hover:bg-secondary-300 transition ease-in-out p-1"
            x-on:click="filters_open = !filters_open">
            <span
                class="font-medium">Done</span>
        </button>
    </div>
</div>

portfolio/templates/portfolio/pages/projects/sidebar_item.html
<template x-if="'{{ technology.display_name|lower }}'.startsWith(search.toLowerCase())">
    <label for="checkbox_{{ technology.name }}" class="px-4 py-2 gap-4 flex flex-row items-center bg-white dark:bg-gray-900 dark:text-white border border-gray-200 rounded shadow dark:border-gray-700 hover:transform hover:scale-105 transition ease-in-out duration-300 hover:shadow-md has-[:checked]:bg-secondary-100 dark:has-[:checked]:bg-secondary-500 has-[:checked]:border-secondary-200 has-[:checked]:text-secondary-800 dark:has-[:checked]:text-gray-900 hover:has-[:checked]:bg-secondary-100 hover:cursor-pointer">
        <input
            id="checkbox_{{ technology.name }}" name="{{ technology.name }}" type="checkbox"
            x-on:click="
                if (filter_technologies.includes('{{ technology.name }}'))
                    filter_technologies.splice(filter_technologies.indexOf('{{ technology.name }}'), 1)
                else
                    filter_technologies.push('{{ technology.name }}')
            "
            x-bind:checked="filter_technologies.includes('{{ technology.name }}')"
            class="w-6 h-6 rounded-full bg-secondary-700 checked:text-white checked:bg-secondary-700 accent-secondary-700 text-secondary-600 border-secondary-300 dark:focus:ring-secondary-400 dark:ring-offset-secondary-800 focus:ring-1 dark:bg-secondary-700 dark:border-secondary-600">
        
        <div class="flex flex-row gap-4 justify-center items-center">
            <div class="flex justify-center items-center w-full w-10 h-10 lg:h-12 lg:w-12">
                <img class="object-fit w-full h-full" src="{{ technology.icon.url }}" alt="{{ technology.name }}">
            </div>
            <span class="font-medium text-sm">{{ technology.display_name }}</span>
        </div>
    </label>
</template>

portfolio/templates/portfolio/pages/projects/sidebar_search.html
<div name="form_search-tech-stack">   
    <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
    <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
        </div>
        <input
            type="search" id="tech-stack-search"
            class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Search languages, frameworks, etc." required name="search_input-tech-stack"
            x-model="search"/>
    </div>
</div>

services/templates/services/_base.html
{% extends 'public/_base.html' %}

templates/_base.html
{% load i18n %}
{% load static %}
{% load django_browser_reload %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta author="Lusayo Nyondo">
        <meta description="My portfolio project.">
        {% block title %}
            <title>Sayo Portfolio</title>
        {% endblock %}

        <link rel="stylesheet" type="text/css" href="{% static 'src/output.css' %}">
        
        <link rel="icon" type="image/svg" href="{% static 'assets/logo.svg' %}">
    </head>
    <body
        x-data="{
            darkMode: {
                on: false,
                toggle() {
                    this.on = !this.on;
                },
            }
        }"
        x-bind:class="{ 'dark': darkMode.on }"
        class="w-screen h-screen overflow-y-hidden min-w-[200px]">
        {% block body %}
        {% endblock %}

        {% django_browser_reload_script %}
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
        <script src="{% static 'js/alpinejs@3.14.3/dist/cdn.min.js' %}" defer></script>
    </body>
</html>

templates/components/navbar_link.html
{% load public_extras %}
<li>
    <a
        href="{% url link_url %}"
        class="{% get_link_class request link_url link_active_class link_inactive_class %}"
        aria-current="page">
        <span>{{ link_text }} </span>
    </a>
</li>

templates/django/forms/widgets/input.html
<input
    class="rounded block w-full border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
    type="{{ widget.type }}"
    name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}
    {% include "django/forms/widgets/attrs.html" %}>